# Place this in the site Nginx config.
# Website root MUST be .../public

location / {
    try_files $uri $uri/ /index.php?$query_string;
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass unix:/tmp/php-cgi-85.sock;
    fastcgi_index index.php;
    include fastcgi.conf;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}

location ~* /\.(git|env|ht) {
    deny all;
}

# Long e-paths need a larger URI buffer
large_client_header_buffers 8 32k;
client_header_buffer_size 16k;
