#!/usr/bin/env node
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {URL} = require('node:url');
const PORT = Number(process.env.PORT || 8080), BASE = (process.env.APP_BASE_URL || `http://localhost:${PORT}`).replace(/\/$/, ''), TOKEN = process.env.API_TOKEN || '', MIN = Number(process.env.MIN_LENGTH || 8), MAX = Number(process.env.MAX_LENGTH || 5000), STORE = process.env.STORE_PATH || path.join(__dirname, 'data.json');
let store = fs.existsSync(STORE) ? JSON.parse(fs.readFileSync(STORE, 'utf8')) : {links: {}, nextId: 1};
function save(){fs.mkdirSync(path.dirname(STORE),{recursive:true});fs.writeFileSync(STORE,JSON.stringify(store,null,2));}
function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':b.length});res.end(b);}
function allowed(raw){const value=/^[a-z][a-z0-9+.-]*:\/\//i.test(raw.trim())?raw.trim():`https://${raw.trim()}`;try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||!u.hostname)return null;const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.local')||/^127\.|^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(h))return null;return value;}catch{return null;}}
function create(url,wanted){const target=allowed(url);if(!target)throw new Error('Invalid URL. Only http/https public URLs are allowed.');if(wanted<MIN||wanted>MAX)throw new Error(`Length must be between ${MIN} and ${MAX}.`);const used=new Set(Object.keys(store.links).map(Number));let length=wanted;while(length<=MAX&&used.has(length))length++;if(length>MAX)throw new Error('No free e-length available in the allowed range.');const id=store.nextId++;store.links[length]={id,length,target,clicks:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),enabled:true,logs:[]};save();return {id,length,target,url:`${BASE}/`+'e'.repeat(length)};}
function body(req,cb){let raw='';req.on('data',x=>{raw+=x;if(raw.length>1e6)req.destroy();});req.on('end',()=>{try{cb(req.headers['content-type']?.startsWith('application/json')?JSON.parse(raw||'{}'):Object.fromEntries(new URLSearchParams(raw)))}catch{cb({})}});}
const server=http.createServer((req,res)=>{const u=new URL(req.url,BASE);if(req.method==='GET'&&u.pathname==='/healthz')return json(res,200,{ok:true,service:'eeee-node'});if(req.method==='GET'&&u.pathname==='/')return json(res,200,{service:'EEEE Long URL',implementation:'node',status:'ok'});if(req.method==='GET'&&/^\/e+$/.test(u.pathname)){const link=store.links[u.pathname.length-1];if(link&&link.enabled){link.clicks++;link.updatedAt=new Date().toISOString();link.logs.push({at:link.updatedAt,ip:req.socket.remoteAddress||'',userAgent:req.headers['user-agent']||'',referer:req.headers.referer||'',uri:req.url});save();res.writeHead(302,{Location:link.target});return res.end();}}if(req.method!=='POST'||u.pathname!=='/api/create')return json(res,404,{success:false,error:'Not found'});body(req,data=>{const auth=String((req.headers.authorization||'').replace(/^Bearer\s+/i,'')||req.headers['x-api-token']||data.token||'');const expected=Buffer.from(TOKEN),actual=Buffer.from(auth);if(!TOKEN||actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return json(res,401,{success:false,error:'Unauthorized'});try{return json(res,200,{success:true,...create(String(data.url||''),Number(data.length||50))})}catch(e){return json(res,400,{success:false,error:e.message})}})});server.listen(PORT,'0.0.0.0',()=>console.log(`EEEE Node backend listening on :${PORT}`));
